NOTICE
Just a trivial year update in NOTICE file.
=> RATIS-875. Bump the copyright year in the NOTICE of thirdparty

misc/pom.xml
Netty jars provides native epoll which is better in performance over NIO. However because of netty shading, the .so files are not shaded correctly. This jira shades the jar's correctly.
https://netty.io/wiki/native-transports.html
=> RATIS-1046. relocate native_epoll.so files correctly to allow use of native epoll on Linux servers.

NOTICE
As Justin Mclean reported during the 0.6.0 vote, this standard phrase is missing from the the thirdpardy NOTICE file:
```
This product includes software developed at
The Apache Software Foundation (http://www.apache.org/).
```
=> RATIS-1293. Add standard ending to thirdparty NOTICE

.github/workflows/ci.yaml
Add a basic Github Actions check to build the package and run existing smoketests.
https://issues.apache.org/jira/browse/RATIS-1343
Push to fork:
https://github.com/adoroszlai/ratis-thirdparty/actions/runs/661309748
```
...
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
...
[INFO] BUILD SUCCESS
```
=> RATIS-1343. Add basic CI check for ratis-thirdparty

pom.xml
Bump Netty version to latest 4.1 release with fix for:
* https://github.com/netty/netty/security/advisories/GHSA-5mcr-gq6c-3hq2
* https://github.com/netty/netty/security/advisories/GHSA-wm47-8v5p-wjpj
https://issues.apache.org/jira/browse/RATIS-1342
Tested locally: built `ratis-thirdparty-misc`, built Ratis with it.  Ran Ratis tests and some Ozone acceptance tests using this custom build.
=> RATIS-1342. Upgrade Netty to 4.1.60.Final

.asf.yaml
Add `.asf.yaml` to `ratis-thirdparty` repo with similar settings as in the main `ratis` repo.  The only differences are in the description and labels.
https://issues.apache.org/jira/browse/RATIS-1346
Notification and merge settings were already tested on the main repo.
=> RATIS-1346. Add .asf.yaml to ratis-thirdparty

test/src/test/java/org/apache/ratis/thirdparty/demo/GrpcSslTest.java, test/src/test/java/org/apache/ratis/thirdparty/demo/GrpcTest.java
Fix intermittent failure due to threading problem in `GrpcSslTest`, and similar one (although not yet encountered) in `GrpcTest`.
Start the server in the main thread, only the blocking call needs to be pushed to a separate thread.
https://issues.apache.org/jira/browse/RATIS-1348
Reproduced the problem by adding `sleep(2000)` before `server.start()` in the original code.  With the fix such delay does not affect client's connection.
CI runs:
https://github.com/adoroszlai/ratis-thirdparty/actions/runs/667445986
https://github.com/adoroszlai/ratis-thirdparty/actions/runs/667453955
https://github.com/adoroszlai/ratis-thirdparty/actions/runs/667456741
https://github.com/adoroszlai/ratis-thirdparty/actions/runs/667461303
=> RATIS-1348. Intermittent failure in GrpcSslTest

pom.xml
Bump Netty version to latest 4.1 release with fix for https://github.com/netty/netty/security/advisories/GHSA-f256-j965-7f32
https://issues.apache.org/jira/browse/RATIS-1355
Tested locally: built `ratis-thirdparty-misc`, built Ratis with it.  Ran Ratis tests and some Ozone acceptance tests using this custom build.
=> RATIS-1355. Upgrade Netty to 4.1.63

pom.xml
RATIS-1355 upgraded Netty due to a CVE, but no matching gRPC was available at that time.  Now the latest gRPC version officially supports Netty 4.1.63.
https://issues.apache.org/jira/browse/RATIS-1466
Built Ratis with the updated thirdparty library, ran tests.
Verified that no native libraries are left unshaded:
```
$ find misc/target/classes/META-INF/native -type f -name '*netty*' -not -name '*ratis_thirdparty*' | wc -l
0
$ unzip -t misc/target/ratis-thirdparty-misc-0.8.0-SNAPSHOT.jar 'META-INF/native/*'
Archive:  misc/target/ratis-thirdparty-misc-0.8.0-SNAPSHOT.jar
testing: META-INF/native/         OK
testing: META-INF/native/liborg_apache_ratis_thirdparty_netty_tcnative_osx_x86_64.jnilib   OK
testing: META-INF/native/liborg_apache_ratis_thirdparty_netty_tcnative_linux_x86_64.so   OK …
```
=> RATIS-1466. Upgrade gRPC to 1.42.1

pom.xml
See https://issues.apache.org/jira/browse/RATIS-1468
=> RATIS-1468. Remove unused log4j dependency from thirdparty pom.xml.

pom.xml
Bump gPRC to 1.43.2, the latest version which supports Netty 4.1.63.
Bump Protobuf to 3.19.2.
https://issues.apache.org/jira/browse/RATIS-1496
Built Ratis with thirdparty upgraded to 0.8.0-SNAPSHOT, ran tests.
Built Ozone with them and ran some acceptance tests (HA, secure HA, compatibility).
CI:
https://github.com/adoroszlai/ratis-thirdparty/runs/4869330477
=> RATIS-1496. Upgrade gRPC to 1.43.2

misc/pom.xml, misc/src/main/appended-resources/META-INF/NOTICE, pom.xml
Ratis Thirdparty bundles `netty-all` with lots of exclusions.  The contents of the `netty-all` JAR may change between releases.  This PR proposes to bundle specific Netty artifacts instead.  This way we could avoid silently adding more Netty code during upgrades.
https://issues.apache.org/jira/browse/RATIS-1514
Built Ratis Thirdparty.
Built Ratis with it, ran unit tests.
Built Ozone with custom Ratis, ran some basic acceptance tests.
Diff of `ratis-thirdparty-misc` jar contents between `master` and this PR:
```diff
--- /dev/fd/12	2022-01-30 20:11:05.974531227 +0100
+++ /dev/fd/13	2022-01-30 20:11:05.975024344 +0100
@@ -39,16 +39,59 @@
testing: META-INF/maven/com.google.protobuf/protobuf-java/pom.properties   OK
testing: META-INF/maven/com.google.protobuf/protobuf-java/pom.xml   OK …
```
=> RATIS-1514. Bundle specific netty artifacts instead of netty-all

.github/workflows/ci.yaml
Do not display transfer progress in CI when downloading plugins and dependencies.
https://issues.apache.org/jira/browse/RATIS-1523
CI
https://github.com/adoroszlai/ratis-thirdparty/runs/5184321559
=> RATIS-1523. Omit download progress in CI build

misc/pom.xml, pom.xml, test/src/test/java/org/apache/ratis/thirdparty/demo/GrpcSslTest.java
* Upgrade gRPC to latest 1.44.0.
* Upgrade Netty to latest 4.1.74.  Netty tcnative version (2.0.48) now comes from Netty POM to ensure consistency.
https://issues.apache.org/jira/browse/RATIS-1515
CI:
https://github.com/adoroszlai/ratis-thirdparty/runs/5186299011#step:5:217
Built locally, verified that all native libraries are shaded:
```
$ unzip -t misc/target/ratis-thirdparty-misc-0.8.0-SNAPSHOT.jar | grep netty_
testing: META-INF/native/liborg_apache_ratis_thirdparty_netty_resolver_dns_native_macos_x86_64.jnilib   OK
testing: META-INF/native/liborg_apache_ratis_thirdparty_netty_tcnative_linux_aarch_64.so   OK
testing: META-INF/native/liborg_apache_ratis_thirdparty_netty_tcnative_linux_x86_64.so   OK
testing: META-INF/native/liborg_apache_ratis_thirdparty_netty_tcnative_osx_aarch_64.jnil …
```
=> RATIS-1515. Upgrade gRPC to 1.44.0, Netty to 4.1.74

pom.xml
This should address [CVE-2022-24823](https://nvd.nist.gov/vuln/detail/CVE-2022-24823).
=> RATIS-1591. Bump netty to 4.1.77

pom.xml
~Upgrade gRPC to 1.48.0, Netty to 4.1.79 in Ratis Thirdparty.~
Upgrade gRPC to 1.48.1.
https://issues.apache.org/jira/browse/RATIS-1632
Regular CI:
~https://github.com/adoroszlai/ratis-thirdparty/runs/7451209538?check_suite_focus=true~
https://github.com/adoroszlai/ratis-thirdparty/runs/7654050988?check_suite_focus=true
~Ran Ratis unit tests with local build of Ratis Thirdparty.  `TestRaftReconfigurationWithGrpc` failed both with and without the change, otherwise OK.~
=> RATIS-1632. Upgrade gRPC to 1.48.1

.github/workflows/ci.yaml
* Upgrade Github Actions action versions to ones that use node16, as node12 is being deprecated: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
* Also upgrade runner to Ubuntu 20.04, because Ubuntu 18.04 is deprecated: https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/
https://issues.apache.org/jira/browse/RATIS-1725
Regular CI:
https://github.com/adoroszlai/ratis-thirdparty/actions/runs/3252226403
=> RATIS-1725. Update github actions for node16

.github/workflows/ci.yaml
Upgrade GitHub actions to `v4` to get Node.js 20.
https://issues.apache.org/jira/browse/RATIS-2015
https://github.com/adoroszlai/ratis-thirdparty/actions/runs/7644612136
=> RATIS-2015. Node.js 16 actions are deprecated

pom.xml, test/src/main/java/org/apache/ratis/thirdparty/demo/common/SslConfig.java
Bump Netty to latest (4.1.109 currently).
I had to tweak cipher list in tests to make `GrpcSslTest` to pass.  It was failing with `StacklessSSLHandshakeException: Connection closed while SSL/TLS handshake was in progress` due to one of the [changes in Netty 4.1.108](https://netty.io/news/2024/03/21/4-1-108-Final.html) related to SSL.
https://issues.apache.org/jira/browse/RATIS-2064
CI:
https://github.com/adoroszlai/ratis-thirdparty/actions/runs/8877229601
=> RATIS-2064. Bump Netty to 4.1.109

.github/workflows/ci.yaml, pom.xml
Create and publish Software Bill of Materials (SBOM) for Ratis Third-party.  (See https://github.com/apache/ratis/pull/1110 for related PR in Ratis.)
https://cwiki.apache.org/confluence/display/SECURITY/Software+Bill+of+Materials+SBOM
https://issues.apache.org/jira/browse/RATIS-2110
CI:
https://github.com/adoroszlai/ratis-thirdparty/actions/runs/9426923225/job/25970427146#step:5:67
=> RATIS-2110. Publish SBOM artifacts

.github/workflows/ci.yaml, pom.xml
- Bump `maven-shade-plugin` to fix:
```
$ mvn artifact:check-buildplan
...
[ERROR] plugin with non-reproducible output: org.apache.maven.plugins:maven-shade-plugin:3.1.1, require minimum 3.5.2
```
- Enable reproducible builds by adding `project.build.outputTimestamp` property.
- Add new step in CI to verify that build is reproducible.
https://issues.apache.org/jira/browse/RATIS-2119
Same steps as in CI.
```
$ mvn --no-transfer-progress -Ptest -Prelease clean install
...
$ mvn --no-transfer-progress -Ptest -Prelease -DskipTests clean verify artifact:compare
...
[INFO] --- maven-artifact-plugin:3.5.1:compare (default-cli) @ ratis-thirdparty ---
...
[INFO] Reproducible Build output summary: 3 files ok
...
[INFO] --- maven-artifact-plugin:3.5.1:compare (default-cli) @ ratis-thirdparty-misc …
```
=> RATIS-2119. Enable reproducible builds

misc/pom.xml, pom.xml, test/pom.xml
see https://issues.apache.org/jira/browse/RATIS-2230
=> RATIS-2230 Bump ratis-thirdparty version to 1.0.9-SNAPSHOT after 1.0.8 release

.github/workflows/ci.yaml
Ubuntu 20.04 is being deprecated: https://github.com/actions/runner-images/issues/11101
Upgrade to 24.04.
https://issues.apache.org/jira/browse/RATIS-2247
CI:
https://github.com/adoroszlai/ratis-thirdparty/actions/runs/13249820869
=> RATIS-2247. Bump GitHub Actions runner to ubuntu-24.04

.gitignore
Make Git ignore `.mvn/develocity/`.
https://issues.apache.org/jira/browse/RATIS-2277
```
$ mvn -Ptest clean verify
$ git status
...
nothing to commit, working tree clean
```
=> RATIS-2277. Ignore `.mvn/.develocity`

pom.xml
Bump Netty to 4.1.119.Final, gRPC to 1.71.0.
https://issues.apache.org/jira/browse/RATIS-2276
https://github.com/adoroszlai/ratis-thirdparty/actions/runs/14279589986
=> RATIS-2276. Bump Netty to 4.1.119.Final, gRPC to 1.71.0

.asf.yaml
- Automatically link mention of RATIS Jira issues in GitHub (e.g. RATIS-2280).
- Change site URL to HTTPS.
https://issues.apache.org/jira/browse/RATIS-2280
Similar config at https://github.com/apache/ratis/blob/master/.asf.yaml
=> RATIS-2280. Autolink Ratis Jira issues in GitHub

.asf.yaml
Set the default commit message to the PR title during merge.  The title can still be edited if needed, but we can avoid picking up single commit's possibly bad message.  (See [.asf.yaml documentation](https://github.com/apache/infrastructure-asfyaml/blob/main/README.md#merge-buttons).)
https://issues.apache.org/jira/browse/RATIS-2297
=> RATIS-2297. Set default commit message to PR title

misc/pom.xml, pom.xml, test/pom.xml
```
mvn versions:set -DnewVersion=1.0.10-SNAPSHOT
```
https://issues.apache.org/jira/browse/RATIS-2298
```
mvn -Ptest clean verify
```
=> RATIS-2298. Bump version to 1.0.10-SNAPSHOT after 1.0.9 release
